# Site settings
title: Sean Bailey
email: sean@seanbailey.io
description: >-
  Designer, developer, and computer science major!
baseurl: ""
url: "https://www.seanbailey.io"
date_format: "%B %d, %Y"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: expanded
  sass_dir: _sass
