# Site settings
title: Sean Bailey
email: sean@seanbailey.io
description: >-
  Designer, developer, and computer science major!
baseurl: ""
url: "https://www.seanbailey.io"
twitter_username: devseanbailey
github_username: sean0x42

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: expanded
  sass_dir: _sass
