# Site settings
title: Sean Bailey
email: sean@seanbailey.io
description: >-
  I'm a designer, developer, and intern at Komatsu.
baseurl: ""
url: "https://www.seanbailey.io"
twitter_username: devseanbailey
github_username: sean0x42

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact
  sass_dir: _sass
